update net04_ext network configuration
eayunstack/fuel-plugin-neutron-ext-net pull request #1
Opened 2017-10-19 02:29 UTC by blkart

update network_type to 'vlan', physical_network to the provider network
and segmentation_id to the max vlan id by user provided configuration.

Signed-off-by: blkart <blkart.org@gmail.com>

2017-10-19 02:56 UTC, huntxu requested changes

2017-10-19 02:56 UTC, huntxu commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +    content => template('ext_net/mysql_update.sh.erb'),
这个文件内容固定，不需要用template，直接用文件就可以了

2017-10-19 02:56 UTC, huntxu commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +    require  => File["/tmp/mysql_neutron_update.sql", "/tmp/mysql_update.sh"]
这里应该使用`refreshonly`属性或者`onlyif`属性，后者需要检查net04_ext这个网络非vlan(但因为多节点下无法确定连接的neutron-server状态所以不是很建议)。然后对`File["/tmp/mysql_neutron_update.sql"]`的关系应该是`subscribe`。

另外这里有个问题是ha模式下多个节点会执行这个sql，sql可能需要处理争抢（比如加锁之类的），另外看能否通过优化sql脚本增加一些过滤条件减少实际update的操作。

2017-10-19 02:56 UTC, huntxu commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +          ~> Exec['mysql_neutron_update']
严格讲这个exec与前面这些资源都没有相关，是比较独立的。唯一相关`neutron-server`需要先启动，`ml2_vlan_allocations`才会新增vlan和physical network和allocated的row，mysql脚本才能正常执行。

2017-10-20 04:20 UTC, huntxu requested changes

2017-10-20 04:20 UTC, huntxu commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +  if member($roles, 'primary-controller') {
单controller的情况也需要处理吧？

2017-10-20 04:25 UTC, huntxu commented
sql执行完之后只是修改了数据库内容，agent端还需要对连着那个网络的路由进行迁移（或者重启），原来连着被修改这个网络的路由才能够正常工作。

2017-10-23 02:31 UTC, huntxu commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +      command     => "/tmp/mysql_update.sh",
这里应该可以不通过脚本运行，直接这里用`mysql`的命令行？

2017-10-23 02:31 UTC, huntxu commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +      command     => "/tmp/mysql_update.sh",
另外需要有个办法避免这个脚本多次运行，有个corner case是部署完成之后，删掉net04_ext之后又建了一个同名的net04_ext，这个操作会将新建的网络的vlan信息强制设置成初始配置。看起来应该判断该网络是否已经是vlan类型了并且加入到是否运行的节点判断那里。

2017-10-23 04:23 UTC, blkart commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +      command     => "/tmp/mysql_update.sh",
```避免这个脚本多次运行``` 是指在多个 controller 节点运行？ 前面已经做过判断了。现在 HA 环境只在 primary-controller 节点运行，非 HA 环境在 controller 节点运行。

2017-10-23 06:11 UTC, huntxu commented on deployment_scripts/puppet/modules/ext_net/manifests/init.pp
> +      command     => "/tmp/mysql_update.sh",
> 避免这个脚本多次运行 是指在多个 controller 节点运行？ 前面已经做过判断了。现在 HA 环境只在 primary-controller 节点运行，非 HA 环境在 controller 节点运行。

不是，多次运行指的是新增节点的时候，这个插件会被再执行一次，这种情况有机会前面说的那个corner case会出现。（虽然通常应该不会发生）

2017-10-23 08:02 UTC, huntxu approved these changes
thanks for the improvement

2017-10-30 02:41 UTC, merged